# Generated by Django 3.1.2 on 2020-12-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_value', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_value', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_card', models.CharField(max_length=10, null=True)),
                ('animal_name', models.CharField(max_length=10, null=True)),
                ('animal_kind', models.CharField(choices=[('С', 'Собака'), ('К', 'Кошка')], max_length=10, null=True)),
                ('animal_gender', models.CharField(choices=[('M', 'Кабель'), ('Ж', 'Сучка')], max_length=10, null=True, verbose_name='Пол')),
                ('animal_ears', models.CharField(choices=[('С', 'Стоячие'), ('П', 'Полустоячие'), ('В', 'Висячие'), ('К', 'Купированные')], max_length=20, null=True)),
                ('animal_tail', models.CharField(choices=[('С', 'Стоячие'), ('П', 'Полустоячие'), ('В', 'Висячие'), ('К', 'Купированные')], max_length=20, null=True)),
                ('animal_age', models.CharField(max_length=20, null=True)),
                ('animal_breed', models.CharField(default='Метис', max_length=50, null=True)),
                ('animal_size', models.CharField(max_length=10, null=True)),
                ('animal_wool', models.CharField(choices=[('К', 'Короткая'), ('О', 'Обычная'), ('Д', 'Длинная')], max_length=10, null=True)),
                ('area', models.CharField(max_length=2, null=True)),
                ('animal_color', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.color')),
                ('animal_weight', models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.weight')),
            ],
        ),
    ]
