# Generated by Django 3.1.2 on 2020-12-23 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_animal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='photo',
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_age',
            field=models.CharField(max_length=20, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_breed',
            field=models.CharField(default='Метис', max_length=50, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_card',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер карточки'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_color',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_ears',
            field=models.CharField(choices=[('С', 'Стоячие'), ('П', 'Полустоячие'), ('В', 'Висячие'), ('К', 'Купированные')], max_length=20, null=True, verbose_name='Уши'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_kind',
            field=models.CharField(choices=[('С', 'Собака'), ('К', 'Кошка')], max_length=10, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_size',
            field=models.CharField(max_length=10, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_tail',
            field=models.CharField(choices=[('С', 'Стоячие'), ('П', 'Полустоячие'), ('В', 'Висячие'), ('К', 'Купированные')], max_length=20, null=True, verbose_name='Хвост'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_weight',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelter.weight', verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_wool',
            field=models.CharField(choices=[('К', 'Короткая'), ('О', 'Обычная'), ('Д', 'Длинная')], max_length=10, null=True, verbose_name='Шерсть'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='area',
            field=models.CharField(max_length=2, null=True, verbose_name='Вольер'),
        ),
    ]
