# Generated by Django 3.1.2 on 2020-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0003_auto_20201223_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, upload_to='animals/%Y/%m/%d'),
        ),
    ]
