# Generated by Django 3.1.2 on 2020-12-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0005_animal_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='user_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Хозяин'),
        ),
    ]
